stages:
  - build_image
  - run_tests

get_docker_image:
  stage: build_image
  script:
    - docker build -t ${CI_REGISTRY_IMAGE}:latest .
    - docker login -u gitlab-ci-token -p ${CI_BUILD_TOKEN} ${CI_REGISTRY}
    - docker push ${CI_REGISTRY_IMAGE} 
  tags:
    - executor:docker
    

run_dq_tests:
  stage: run_tests
  image: ${CI_REGISTRY_IMAGE}:latest
  script:
    - cp ${gel_config} ${CI_PROJECT_DIR}/.gel_config
    - ls -lh .gel_config
    - cat .gel_config
    - Rscript test.r
  tags:
    - ou:cln
  only:
    refs:
      - master

