make_image:
  except:
    - schedules
  script:
    - docker build -t ${CI_REGISTRY_IMAGE}:latest .
    - docker login -u gitlab-ci-token -p ${CI_BUILD_TOKEN} ${CI_REGISTRY}
    - docker push ${CI_REGISTRY_IMAGE} 
  tags:
    - executor:docker
    

run_dq_tests:
  image: registry.gitlab.com/genomicsengland/dataquality/gitlab-test:latest
  script:
    - echo ${CI_JOB_TOKEN}
    - cp ${gel_config} ${CI_PROJECT_DIR}/.gel_config
    - ls -lh .gel_config
    - 'curl --location --output artifacts.zip --header "JOB-TOKEN: $CI_JOB_TOKEN" "https://genomicsengland.gitlab.io/api/v4/projects/$CI_PROJECT_ID/jobs/artifacts/master/download?job=run_dq_test"'
    - ls -lh artifacts.zip
    - cat artifacts.zip
    - unzip artifacts.zip
    - ls -lh test-data.txt
    - Rscript test.r
    - ping 10.1.24.38 -c 2
  tags:
    - location:ukc_fixed
    - executor:docker
  artifacts:
    paths:
    - test-data.txt
    expire_in: 1 week
  only:
    refs:
      - schedules

