make_image:
  except:
    - schedules
  script:
    - docker build -t ${CI_REGISTRY_IMAGE}:latest .
    - docker login -u gitlab-ci-token -p ${CI_BUILD_TOKEN} ${CI_REGISTRY}
    - docker push ${CI_REGISTRY_IMAGE} 
  tags:
    - executor:docker
    

run_dq_tests:
  image: registry.gitlab.com/genomicsengland/dataquality/gitlab-test:latest
  script:
    - cp ${gel_config} ${CI_PROJECT_DIR}/.gel_config
    - ls -lh .gel_config
    - cat .gel_config
    - Rscript test.r
    - sshpass -p ${pword} scp test.r sthompson@10.1.24.38:/cdt_share/cdt/test.r 
  tags:
    - ou:cln
    - executor:docker
  only:
    refs:
      - schedules

