stages:
  - run_tests

run_dq_tests:
  stage: run_tests
  image: ${CI_REGISTRY}/genomicsengland/dataquality/cdt-docker/cdt-docker:${cdq_version}
  script:
    - cp ${cdt_del_deploy} ${CI_PROJECT_DIR}/.gel_config
    - ls -lh .gel_config
    - cat .gel_config
    - Rscript test.r
  tags:
    - ou:cln
  only:
    refs:
      - master

